### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by pankajmt** [vchinnipilli/kubestrike#9]
Novice in Python and its ecosystem 

pip install -r requirements.txt
Collecting colorama==0.4.4 (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/44/98/5b86278fbbf250d239ae0ecb724f8572af1c91f4a11edf4d36a206189440/colorama-0.4.4-py2.py3-none-any.whl
Collecting colored==1.4.2 (from -r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/b2/16/04827e24c14266d9161bd86bad50069fea453fa006c3d2b31da39251184a/colored-1.4.2.tar.gz (56kB)
     |████████████████████████████████| 61kB 4.0MB/s
Collecting figlet==0.0.1 (from -r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/cc/43/b0773f2deb50509b572206256069b2e0bb2babf406b39a116b1dc29e002d/figlet-0.0.1-py3-none-any.whl
Collecting progress==1.5 (from -r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/38/ef/2e887b3d2b248916fc2121889ce68af8a16aaddbe82f9ae6533c24ff0d2b/progress-1.5.tar.gz
Collecting prompt-toolkit==1.0.15 (from -r requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/04/d1/c6616dd03701e7e2073f06d5c3b41b012256e42b72561f16a7bd86dd7b43/prompt_toolkit-1.0.15-py3-none-any.whl (247kB)
     |████████████████████████████████| 256kB 5.8MB/s
Collecting SelectMenu (from -r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/cd/b9/8078a7f34c5b877e7fa26e5c5c5f62cbc765d44c949dd672a29aef62089a/SelectMenu-1.0.0b2.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /Users/ptolani/greaterbank/infosec/kubestrike/env/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/8r/g00ct8cd3cd2068_k9xqdgnh0000gn/T/pip-install-_x5wypri/SelectMenu/setup.py'"'"'; __file__='"'"'/private/var/folders/8r/g00ct8cd3cd2068_k9xqdgnh0000gn/T/pip-install-_x5wypri/SelectMenu/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /private/var/folders/8r/g00ct8cd3cd2068_k9xqdgnh0000gn/T/pip-install-_x5wypri/SelectMenu/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/8r/g00ct8cd3cd2068_k9xqdgnh0000gn/T/pip-install-_x5wypri/SelectMenu/setup.py", line 5, in <module>
        from selectmenu import __author__, __version__
      File "/private/var/folders/8r/g00ct8cd3cd2068_k9xqdgnh0000gn/T/pip-install-_x5wypri/SelectMenu/selectmenu/__init__.py", line 4, in <module>
        from selectmenu.core import SelectMenu
      File "/private/var/folders/8r/g00ct8cd3cd2068_k9xqdgnh0000gn/T/pip-install-_x5wypri/SelectMenu/selectmenu/core.py", line 6, in <module>
        from prompt_toolkit.token import Token
    ModuleNotFoundError: No module named 'prompt_toolkit'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by kubestrike** [comment]
Hi @pankajmt,

As advised in the README, please issue the commands in the below mentioned order.

$ pip install prompt-toolkit==1.0.15 
$ pip install kubestrike

Regards,
Vasant

**Comment by kubestrike** [comment]
Hi @pankajmt ,

Hope the above solution has resolved the issue. Closing this for now.

Please open a new one if you still have any issues.

Regards,
Vasant

**Comment by dnx-seek** [comment]
The above step is missing from the [docs](https://www.kubestriker.io/Clone-the-repo-and-install#Clonetherepoandinstall)

I'm not sure if they're on github to contribute to, so just putting the note on this issue to suggest that one is updated.
